
[node]
# Bind address for the node
# type:string,ip
peering_port = 44075

[node.websocket]

# WebSocket server bind address.
# type:string,ip
address = "::ffff:0.0.0.0"
# Enable or disable WebSocket server.
# type:bool
enable = true

[rpc]

# Enable or disable RPC.
# type:bool
enable = true
